---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: moderator
  namespace: moderator-stage
  labels:
    app: moderator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moderator
  template:
    metadata:
      labels:
        app: moderator
    spec:
      containers:
        - name: moderator-web
          image: 783633885093.dkr.ecr.us-west-2.amazonaws.com/moderator:a1e93718831a1ddd0ac509d0509cb915bfe19595
          ports:
            - containerPort: 8000
          envFrom:
          - configMapRef:
              name: moderator-stage
          - secretRef:
              name: moderator-stage
